---
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes:
        - 200
        - 301
        - 302
        - 303
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true
serviceMonitor:
  enabled: true
  defaults:
  additionalRelabeling: 
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.blackbox:9115
  targets:
  - name: google 
    url: https://www.google.com


...
